# generated by datamodel-codegen:
#   filename:  rdap_response.json
#   timestamp: 2026-01-13T10:32:25+00:00

from __future__ import annotations

from datetime import date, time
from enum import Enum, IntEnum
from ipaddress import IPv4Address, IPv6Address
from typing import Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class UniqueStringArray(RootModel[list[str]]):
    root: list[str]


class PositiveInteger(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class StringArray(RootModel[list[str]]):
    root: list[str]


class Datetime(RootModel[str]):
    root: str


class Uri(RootModel[AnyUrl]):
    root: AnyUrl


class Ipv4(RootModel[IPv4Address]):
    root: IPv4Address


class Ipv6(RootModel[IPv6Address]):
    root: IPv6Address


class Ip(RootModel[Ipv4 | Ipv6]):
    root: Ipv4 | Ipv6


class RirBasicType(Enum):
    DIRECT_ALLOCATION = 'DIRECT ALLOCATION'
    DIRECT_ASSIGNMENT = 'DIRECT ASSIGNMENT'
    REALLOCATION = 'REALLOCATION'
    REASSIGNMENT = 'REASSIGNMENT'
    ALLOCATED_UNSPECIFIED = 'ALLOCATED UNSPECIFIED'
    ALLOCATED_BY_RIR = 'ALLOCATED-BY-RIR'
    ALLOCATED_BY_LIR = 'ALLOCATED-BY-LIR'


class RirType(RootModel[RirBasicType | str]):
    root: RirBasicType | str


class LdhName(
    RootModel[
        constr(
            pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$'
        )
    ]
):
    root: constr(
        pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$'
    )


class UnicodeName(RootModel[str]):
    root: str


class DomainName(RootModel[LdhName | UnicodeName]):
    root: LdhName | UnicodeName


class EventAction(Enum):
    registration = 'registration'
    reregistration = 'reregistration'
    last_changed = 'last changed'
    expiration = 'expiration'
    deletion = 'deletion'
    reinstantiation = 'reinstantiation'
    transfer = 'transfer'
    locked = 'locked'
    unlocked = 'unlocked'
    last_update_of_RDAP_database = 'last update of RDAP database'
    registrar_expiration = 'registrar expiration'
    enum_validation_expiration = 'enum validation expiration'


class NoticeType(Enum):
    result_set_truncated_due_to_authorization = (
        'result set truncated due to authorization'
    )
    result_set_truncated_due_to_excessive_load = (
        'result set truncated due to excessive load'
    )
    result_set_truncated_due_to_unexplainable_reasons = (
        'result set truncated due to unexplainable reasons'
    )
    object_truncated_due_to_authorization = 'object truncated due to authorization'
    object_truncated_due_to_excessive_load = 'object truncated due to excessive load'
    object_truncated_due_to_unexplainable_reasons = (
        'object truncated due to unexplainable reasons'
    )


class StatusValue(Enum):
    validated = 'validated'
    renew_prohibited = 'renew prohibited'
    update_prohibited = 'update prohibited'
    transfer_prohibited = 'transfer prohibited'
    delete_prohibited = 'delete prohibited'
    client_renew_prohibited = 'client renew prohibited'
    server_renew_prohibited = 'server renew prohibited'
    client_update_prohibited = 'client update prohibited'
    server_update_prohibited = 'server update prohibited'
    client_transfer_prohibited = 'client transfer prohibited'
    server_transfer_prohibited = 'server transfer prohibited'
    client_delete_prohibited = 'client delete prohibited'
    server_delete_prohibited = 'server delete prohibited'
    client_hold = 'client hold'
    server_hold = 'server hold'
    proxy = 'proxy'
    private = 'private'
    removed = 'removed'
    obscured = 'obscured'
    associated = 'associated'
    active = 'active'
    inactive = 'inactive'
    locked = 'locked'
    pending_create = 'pending create'
    pending_renew = 'pending renew'
    pending_transfer = 'pending transfer'
    pending_update = 'pending update'
    pending_delete = 'pending delete'
    pending_restore = 'pending restore'
    auto_renew_period = 'auto renew period'
    redemption_period = 'redemption period'
    renew_period = 'renew period'
    transfer_period = 'transfer period'
    add_period = 'add period'


class Status(RootModel[list[StatusValue | str]]):
    root: list[StatusValue | str]


class Port43(
    RootModel[
        Ip
        | constr(
            pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$'
        )
    ]
):
    root: Ip | constr(
        pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$'
    )


class Lang(RootModel[constr(pattern=r'[a-z]{2}(-[A-Z][a-zA-Z]*(\-[A-Z]{2})?)?')]):
    root: constr(pattern=r'[a-z]{2}(-[A-Z][a-zA-Z]*(\-[A-Z]{2})?)?')


class Country(RootModel[str]):
    root: str


class Rel(Enum):
    about = 'about'
    alternate = 'alternate'
    appendix = 'appendix'
    archives = 'archives'
    author = 'author'
    blocked_by = 'blocked-by'
    bookmark = 'bookmark'
    canonical = 'canonical'
    chapter = 'chapter'
    cite_as = 'cite-as'
    collection = 'collection'
    contents = 'contents'
    convertedFrom = 'convertedFrom'
    copyright = 'copyright'
    create_form = 'create-form'
    current = 'current'
    describedby = 'describedby'
    describe = 'describe'
    disclosure = 'disclosure'
    dns_prefetch = 'dns-prefetch'
    duplicate = 'duplicate'
    edit = 'edit'
    edit_form = 'edit-form'
    edit_media = 'edit-media'
    enclosure = 'enclosure'
    first = 'first'
    glossary = 'glossary'
    help = 'help'
    hosts = 'hosts'
    hub = 'hub'
    icon = 'icon'
    index_ = 'index'
    item = 'item'
    last = 'last'
    latest_version = 'latest-version'
    license = 'license'
    lrdd = 'lrdd'
    memento = 'memento'
    monitor = 'monitor'
    monitor_group = 'monitor-group'
    next = 'next'
    next_archive = 'next-archive'
    nofollow = 'nofollow'
    noreferrer = 'noreferrer'
    original = 'original'
    payment = 'payment'
    pingback = 'pingback'
    preconnect = 'preconnect'
    predecessor_version = 'predecessor-version'
    prefecth = 'prefecth'
    preload = 'preload'
    prerender = 'prerender'
    prev = 'prev'
    preview = 'preview'
    previous = 'previous'
    prev_archive = 'prev-archive'
    profile = 'profile'
    related = 'related'
    replies = 'replies'
    restconf = 'restconf'
    search = 'search'
    section = 'section'
    self = 'self'
    service = 'service'
    start = 'start'
    stylesheet = 'stylesheet'
    subsection = 'subsection'
    successor_version = 'successor-version'
    tag = 'tag'
    terms_of_service = 'terms-of-service'
    timegate = 'timegate'
    timemap = 'timemap'
    type = 'type'
    up = 'up'
    version_history = 'version-history'
    via = 'via'
    webmention = 'webmention'
    working_copy = 'working-copy'
    working_copy_of = 'working-copy-of'


class Link(BaseModel):
    value: Uri | None = None
    rel: str | None = None
    href: Uri | None = None
    hreflang: list[Lang] | None = None
    title: str | None = None
    media: str | None = None
    type: str | None = None


class Links(RootModel[list[Link]]):
    root: list[Link]


class EventWithoutActor(BaseModel):
    eventAction: EventAction | str | None = None
    eventDate: Datetime | None = None
    links: Links | None = None


class Event(EventWithoutActor):
    eventActor: str | None = None


class Events(RootModel[list[Event]]):
    root: list[Event]


class Notice(BaseModel):
    title: str | None = None
    type: NoticeType | str | None = None
    description: StringArray | None = None
    links: Links | None = None


class Notices(RootModel[list[Notice]]):
    root: list[Notice]


class Remarks(RootModel[list[Notice]]):
    root: list[Notice]


class PublicId(BaseModel):
    type: str
    identifier: str


class PublicIds(RootModel[list[PublicId]]):
    root: list[PublicId]


class RdapResponseCommon(BaseModel):
    rdapConformance: UniqueStringArray | None = None
    lang: Lang | None = None
    notices: Notices | None = None


class RdapErrorObject(BaseModel):
    errorCode: PositiveInteger
    title: str | None = None
    description: StringArray | None = None


class IpAddresses(BaseModel):
    v6: list[Ipv6] | None = None
    v4: list[Ipv4] | None = None


class RdapCommon(BaseModel):
    handle: str | None = None
    status: UniqueStringArray | None = None
    port43: Port43 | None = None
    publicIds: PublicIds | None = None
    events: Events | None = None
    remarks: Remarks | None = None
    links: Links | None = None


class StringOrStringArray(RootModel[list[str]]):
    root: list[str]


class Language(RootModel[constr(pattern=r'[a-z]{2}(-[A-Z][a-zA-Z]*(\-[A-Z]{2})?)?')]):
    root: constr(pattern=r'[a-z]{2}(-[A-Z][a-zA-Z]*(\-[A-Z]{2})?)?')


class TelUri(
    RootModel[
        constr(
            pattern=r'^tel:((?:\+[\d().-]*\d[\d().-]*|[0-9A-F*#().-]*[0-9A-F*#][0-9A-F*#().-]*(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*;phone-context=(?:\+[\d().-]*\d[\d().-]*|(?:[a-z0-9]\.|[a-z0-9][a-z0-9-]*[a-z0-9]\.)*(?:[a-z]|[a-z][a-z0-9-]*[a-z0-9])))(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*(?:,(?:\+[\d().-]*\d[\d().-]*|[0-9A-F*#().-]*[0-9A-F*#][0-9A-F*#().-]*(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*;phone-context=\+[\d().-]*\d[\d().-]*)(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*)*)$'
        )
    ]
):
    root: constr(
        pattern=r'^tel:((?:\+[\d().-]*\d[\d().-]*|[0-9A-F*#().-]*[0-9A-F*#][0-9A-F*#().-]*(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*;phone-context=(?:\+[\d().-]*\d[\d().-]*|(?:[a-z0-9]\.|[a-z0-9][a-z0-9-]*[a-z0-9]\.)*(?:[a-z]|[a-z][a-z0-9-]*[a-z0-9])))(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*(?:,(?:\+[\d().-]*\d[\d().-]*|[0-9A-F*#().-]*[0-9A-F*#][0-9A-F*#().-]*(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*;phone-context=\+[\d().-]*\d[\d().-]*)(?:;[a-z\d-]+(?:=(?:[a-z\d\[\]\/:&+$_!~*\'().-]|%[\dA-F]{2})+)?)*)*)$'
    )


class GeoUri(
    RootModel[
        constr(pattern=r'geo:([\-0-9.]+),([\-0-9.]+)(?:,([\-0-9.]+))?(?:\?(.*))?$')
    ]
):
    root: constr(pattern=r'geo:([\-0-9.]+),([\-0-9.]+)(?:,([\-0-9.]+))?(?:\?(.*))?$')


class UtcOffset(RootModel[constr(pattern=r'^(([-+]\d{1,2}):?(\d{2})?)?$')]):
    root: constr(pattern=r'^(([-+]\d{1,2}):?(\d{2})?)?$')


class Timestamp(RootModel[time]):
    root: time


class DateOrTime(RootModel[date | AwareDatetime]):
    root: date | AwareDatetime


class DateAndOrTime(RootModel[DateOrTime | Timestamp]):
    root: DateOrTime | Timestamp


class Email(RootModel[str]):
    root: str


class MediatypeType(RootModel[constr(pattern=r'^\w+/[-.\w]+(?:\+[-.\w]+)?$')]):
    root: constr(pattern=r'^\w+/[-.\w]+(?:\+[-.\w]+)?$')


class GroupType(RootModel[constr(pattern=r'^[a-zA-Z0-9\-]+$')]):
    root: constr(pattern=r'^[a-zA-Z0-9\-]+$')


class TagType(Enum):
    home = 'home'
    work = 'work'


class TelType(Enum):
    text = 'text'
    voice = 'voice'
    fax = 'fax'
    cell = 'cell'
    video = 'video'
    pager = 'pager'
    textphone = 'textphone'
    main_number = 'main-number'


class RelatedType(Enum):
    contact = 'contact'
    acquaintance = 'acquaintance'
    friend = 'friend'
    met = 'met'
    co_worker = 'co-worker'
    colleague = 'colleague'
    co_resident = 'co-resident'
    neighbor = 'neighbor'
    child = 'child'
    parent = 'parent'
    sibling = 'sibling'
    spouse = 'spouse'
    kin = 'kin'
    muse = 'muse'
    crush = 'crush'
    date = 'date'
    sweetheart = 'sweetheart'
    me = 'me'
    agent = 'agent'
    emergency = 'emergency'


class IndexType(RootModel[constr(pattern=r'^[1-9]?[0-9]*$')]):
    root: constr(pattern=r'^[1-9]?[0-9]*$')


class ExpertiseLevelType(Enum):
    beginner = 'beginner'
    average = 'average'
    expert = 'expert'


class HobbyLevelType(Enum):
    high = 'high'
    medium = 'medium'
    low = 'low'


class PrefType(RootModel[constr(pattern=r'^[1-9]?[0-9]{1}$|^100$')]):
    root: constr(pattern=r'^[1-9]?[0-9]{1}$|^100$')


class CalscaleType(RootModel[Literal['gregorian']]):
    root: Literal['gregorian']


class TelTypeArray(RootModel[list[TelType | TagType]]):
    root: list[TelType | TagType]


class TagTypeArray(RootModel[list[TagType]]):
    root: list[TagType]


class RelatedTypeArray(RootModel[list[RelatedType]]):
    root: list[RelatedType]


class PidTypeArray(RootModel[list[constr(pattern=r'^[0-9]+(\.[0-9]+)?$')]]):
    root: list[constr(pattern=r'^[0-9]+(\.[0-9]+)?$')]


class FnType(RootModel[list[str]]):
    root: list[str] = Field(..., min_length=1)


class NType(RootModel[list[StringOrStringArray]]):
    root: list[StringOrStringArray]


class GenderType(Enum):
    field_ = ''
    M = 'M'
    F = 'F'
    O = 'O'
    N = 'N'
    U = 'U'


class AdrType(RootModel[list[StringOrStringArray]]):
    root: list[StringOrStringArray]


class KindType(Enum):
    individual = 'individual'
    group = 'group'
    org = 'org'
    location = 'location'
    application = 'application'
    device = 'device'


class ClientpidmapType(RootModel[constr(pattern=r'^[0-9]+;(\w+:(\/?\/?)[^\s]+)$')]):
    root: constr(pattern=r'^[0-9]+;(\w+:(\/?\/?)[^\s]+)$')


class AnyParamType(RootModel[dict[constr(pattern=r'^x-'), StringOrStringArray]]):
    root: dict[constr(pattern=r'^x-'), StringOrStringArray]


class AnyType(RootModel[str | bool | float | list[Any] | dict[str, Any]]):
    root: str | bool | float | list[Any] | dict[str, Any]


class Vcard(BaseModel):
    pass


class IpVersion(Enum):
    v4 = 'v4'
    v6 = 'v6'


class IpnetworkClass(RootModel[Literal['ip network']]):
    root: Literal['ip network']


class AutnumClass(RootModel[Literal['autnum']]):
    root: Literal['autnum']


class Autnum(RootModel[conint(ge=0, le=4294967295)]):
    root: conint(ge=0, le=4294967295)


class EntityClass(RootModel[Literal['entity']]):
    root: Literal['entity']


class EntityRole(Enum):
    registrant = 'registrant'
    technical = 'technical'
    administrative = 'administrative'
    abuse = 'abuse'
    billing = 'billing'
    registrar = 'registrar'
    reseller = 'reseller'
    sponsor = 'sponsor'
    proxy = 'proxy'
    notifications = 'notifications'
    noc = 'noc'


class NameserverClass(RootModel[Literal['nameserver']]):
    root: Literal['nameserver']


class DomainClass(RootModel[Literal['domain']]):
    root: Literal['domain']


class VariantRelation(Enum):
    registered = 'registered'
    unregistered = 'unregistered'
    registration_restricted = 'registration restricted'
    open_registration = 'open registration'
    conjoined = 'conjoined'


class DnssecAlgorithm(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7
    integer_8 = 8
    integer_10 = 10
    integer_12 = 12
    integer_13 = 13
    integer_14 = 14
    integer_15 = 15
    integer_16 = 16


class HexString(RootModel[constr(pattern=r'[0-9a-fA-F]+')]):
    root: constr(pattern=r'[0-9a-fA-F]+')


class DigestType(IntEnum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4


class DsDatum(BaseModel):
    keyTag: PositiveInteger | None = None
    algorithm: DnssecAlgorithm | None = None
    digest: HexString | None = None
    digestType: DigestType | None = None
    events: Events | None = None
    links: Links | None = None


class DsData(RootModel[list[DsDatum]]):
    root: list[DsDatum]


class Flags(IntEnum):
    integer_0 = 0
    integer_256 = 256
    integer_257 = 257


class KeyDatum(BaseModel):
    flags: Flags | None = None
    protocol: Literal[3] = 3
    publicKey: str | None = None
    algorithm: DnssecAlgorithm | None = None
    events: Events | None = None
    links: Links | None = None


class KeyData(RootModel[list[KeyDatum]]):
    root: list[KeyDatum]


class SecureDNS(BaseModel):
    zoneSigned: bool | None = None
    delegationSigned: bool | None = None
    maxSigLife: PositiveInteger | None = None
    dsData: DsData | None = None
    keyData: KeyData | None = None


class VariantName(BaseModel):
    ldhName: LdhName | None = None
    unicodeName: UnicodeName | None = None


class Variant(BaseModel):
    relation: list[VariantRelation] | None = None
    idnTable: str | None = None
    variantNames: list[VariantName] | None = None


class RdapHelp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rdapConformance: UniqueStringArray | None = None
    lang: Lang | None = None
    notices: Notices | None = None


class RdapError1(RdapResponseCommon, RdapErrorObject):
    pass


class RdapError(RootModel[RdapError1 | RdapErrorObject]):
    root: RdapError1 | RdapErrorObject


class VcardArray(RootModel[list[Any]]):
    root: list[Any]


class RdapNameserverObject(RdapCommon):
    objectClassName: NameserverClass
    ldhName: LdhName
    unicodeName: UnicodeName | None = None
    ipAddresses: IpAddresses | None = None
    entities: list[RdapEntityObject] | None = None


class RdapEntityObject(RdapCommon):
    objectClassName: EntityClass
    handle: str | None = None
    vcardArray: VcardArray | None = None
    roles: list[EntityRole] | None = None
    entities: list[RdapEntityObject] | None = None
    asEventActor: list[EventWithoutActor] | None = None
    publicIds: PublicIds | None = None
    networks: list[RdapIpnetworkObject] | None = None
    autnums: list[RdapAutnumObject] | None = None


class RdapIpnetworkObject(RdapCommon):
    objectClassName: IpnetworkClass
    startAddress: Ip | None = None
    endAddress: Ip | None = None
    ipVersion: IpVersion | None = None
    name: str | None = None
    type: RirType | None = None
    country: Country | None = None
    parentHandle: str | None = None
    entities: list[RdapEntityObject] | None = None
    nicbr_autnum: int | None = None


class RdapAutnumObject(RdapCommon):
    objectClassName: AutnumClass
    startAutnum: Autnum | None = None
    endAutnum: Autnum | None = None
    name: str | None = None
    type: RirType | None = None
    country: Country | None = None
    entities: list[RdapEntityObject] | None = None


class RdapNameservers(RdapResponseCommon):
    nameserverSearchResults: list[RdapNameserverObject] = Field(..., min_length=1)


class RdapEntities(RdapResponseCommon):
    entitySearchResults: list[RdapEntityObject] = Field(..., min_length=1)


class RdapDomainObject(RdapCommon):
    objectClassName: DomainClass
    ldhName: LdhName
    unicodeName: UnicodeName | None = None
    nameservers: list[RdapNameserverObject] | None = None
    secureDNS: SecureDNS | None = None
    variants: list[Variant] | None = None
    entities: list[RdapEntityObject] | None = None
    network: RdapIpnetworkObject | None = None


class RdapDomains(RdapResponseCommon):
    domainSearchResults: list[RdapDomainObject] = Field(..., min_length=1)


class RdapNameserver(RdapResponseCommon, RdapNameserverObject):
    pass


class RdapEntity(RdapResponseCommon, RdapEntityObject):
    pass


class RdapIpnetwork(RdapResponseCommon, RdapIpnetworkObject):
    pass


class RdapAutnum(RdapResponseCommon, RdapAutnumObject):
    pass


class RdapDomain(RdapResponseCommon, RdapDomainObject):
    pass


class Model(
    RootModel[
        RdapHelp
        | RdapError
        | RdapNameserver
        | RdapNameservers
        | RdapEntity
        | RdapEntities
        | RdapDomain
        | RdapDomains
        | RdapIpnetwork
        | RdapAutnum
    ]
):
    root: (
        RdapHelp
        | RdapError
        | RdapNameserver
        | RdapNameservers
        | RdapEntity
        | RdapEntities
        | RdapDomain
        | RdapDomains
        | RdapIpnetwork
        | RdapAutnum
    )


RdapNameserverObject.model_rebuild()
RdapEntityObject.model_rebuild()
RdapNameserver.model_rebuild()
RdapEntity.model_rebuild()
