"""invite_link

Revision ID: 0e7c820161e7
Revises: 13f930f91b91
Create Date: 2025-03-26 16:22:03.513457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0e7c820161e7'
down_revision: Union[str, None] = '13f930f91b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_link', sa.Column('count_of_entries', sa.Integer(), nullable=True, comment='Количество допустимых использований'))
    op.drop_column('invite_link', 'used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_link', sa.Column('used', sa.BOOLEAN(), nullable=False))
    op.drop_column('invite_link', 'count_of_entries')
    # ### end Alembic commands ###
