"""Comment on network map

Revision ID: 13f930f91b91
Revises: 3ac933babdaa
Create Date: 2025-03-17 16:59:33.109574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '13f930f91b91'
down_revision: Union[str, None] = '3ac933babdaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_comment',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор ip адреса'),
    sa.Column('parent_comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор родительского коммента'),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор пользователя, оставившего коммент'),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Комментарий'),
    sa.ForeignKeyConstraint(['ip_id'], ['ip.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['node_comment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для комментариев на узле на карте сети'
    )
    op.create_table('l4_software_vulnerability_comment',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('l4_software_vulnerability_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор уязвимости на софте на l4'),
    sa.Column('parent_comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор родительского коммента'),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Комментарий'),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор пользователя, оставившего коммент'),
    sa.ForeignKeyConstraint(['l4_software_vulnerability_id'], ['l4_software_vulnerability.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['l4_software_vulnerability_comment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для комментариев на уязвимости L4'
    )
    op.create_table('l7_software_vulnerability_comment',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('l7_software_vulnerability_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор уязвимости на софте на l7'),
    sa.Column('parent_comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор родительского коммента'),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Комментарий'),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор пользователя, оставившего коммент'),
    sa.ForeignKeyConstraint(['l7_software_vulnerability_id'], ['l7_software_vulnerability.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['l7_software_vulnerability_comment.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для комментариев на уязвимости L7'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l7_software_vulnerability_comment')
    op.drop_table('l4_software_vulnerability_comment')
    op.drop_table('node_comment')
    # ### end Alembic commands ###
