"""software_divide

Revision ID: 1bb9a386a83d
Revises: bfa92278e898
Create Date: 2025-05-23 11:14:31.609758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1bb9a386a83d'
down_revision: Union[str, None] = 'bfa92278e898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_software_type',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Наименование типа софта'),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для типа софта'
    )
    op.create_table('d_software_version',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Версия софта'),
    sa.Column('build', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Билд софта'),
    sa.Column('cpe23', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='CPE23 строка софта'),
    sa.Column('software_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор софта'),
    sa.ForeignKeyConstraint(['software_id'], ['d_software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для типа софта'
    )
    op.create_index(op.f('ix_d_software_version_build'), 'd_software_version', ['build'], unique=False)
    op.create_index(op.f('ix_d_software_version_cpe23'), 'd_software_version', ['cpe23'], unique=False)
    op.create_index(op.f('ix_d_software_version_version'), 'd_software_version', ['version'], unique=False)
    op.add_column('d_software', sa.Column('type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор типа софта'))
    op.create_index(op.f('ix_d_software_product'), 'd_software', ['product'], unique=False)
    op.create_foreign_key(None, 'd_software', 'd_software_type', ['type_id'], ['id'])
    op.drop_column('d_software', 'type')
    op.drop_column('d_software', 'version')
    op.drop_column('d_software', 'patch')
    op.drop_column('d_software', 'platform')
    op.drop_column('d_software', 'build')
    op.drop_column('d_software', 'cpe23')
    op.create_index(op.f('ix_d_vendor_name'), 'd_vendor', ['name'], unique=False)
    op.create_foreign_key(None, 'ip', 'network', ['network_id'], ['id'], use_alter=True)
    op.add_column('l4_software', sa.Column('software_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор ПО'))
    op.drop_constraint('l4_software_software_id_fkey', 'l4_software', type_='foreignkey')
    op.create_foreign_key(None, 'l4_software', 'd_software_version', ['software_version_id'], ['id'])
    op.drop_column('l4_software', 'software_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('l4_software', sa.Column('software_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор ПО'))
    op.drop_constraint(None, 'l4_software', type_='foreignkey')
    op.create_foreign_key('l4_software_software_id_fkey', 'l4_software', 'd_software', ['software_id'], ['id'])
    op.drop_column('l4_software', 'software_version_id')
    op.drop_constraint(None, 'ip', type_='foreignkey')
    op.drop_index(op.f('ix_d_vendor_name'), table_name='d_vendor')
    op.add_column('d_software', sa.Column('cpe23', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Строка CPE23'))
    op.add_column('d_software', sa.Column('build', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Билд софта'))
    op.add_column('d_software', sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Платформа софта'))
    op.add_column('d_software', sa.Column('patch', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Патч софта'))
    op.add_column('d_software', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Версия софта'))
    op.add_column('d_software', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Тип софта'))
    op.drop_constraint(None, 'd_software', type_='foreignkey')
    op.drop_index(op.f('ix_d_software_product'), table_name='d_software')
    op.drop_column('d_software', 'type_id')
    op.drop_index(op.f('ix_d_software_version_version'), table_name='d_software_version')
    op.drop_index(op.f('ix_d_software_version_cpe23'), table_name='d_software_version')
    op.drop_index(op.f('ix_d_software_version_build'), table_name='d_software_version')
    op.drop_table('d_software_version')
    op.drop_table('d_software_type')
    # ### end Alembic commands ###
