"""change_tasks_add_interfaces_and_web_archives

Revision ID: 2c3a39215b7b
Revises: 747fefc50024
Create Date: 2026-02-06 17:24:47.134288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from setezor.models.base import generate_unique_id
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '2c3a39215b7b'
down_revision: Union[str, None] = '747fefc50024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    connection = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setezor_agent_network_interface',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор агента'),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='IP интерфейса'),
    sa.Column('mac', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='MAC интерфейса'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Название интерфейса'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['setezor_agent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для хранения интерфейсов агента'
    )

    op.add_column('network_ip', sa.Column('interface_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор интерфейса'))
    op.create_foreign_key(None, 'network_ip', 'setezor_agent_network_interface', ['interface_id'], ['id'])

    interfaces = list(
        connection.execute(sa.text(
            "SELECT network_ip.id as ip_id, network_ip.ip, network_mac.mac, network_mac.name, setezor_agent_in_project.agent_id FROM network_ip "
            "join network_mac on network_mac.id = network_ip.mac_id "
            "join object on object.id = network_mac.object_id "
            "join setezor_agent_in_project on setezor_agent_in_project.id = object.agent_id "
            "where network_mac.name != ''"
        ))
    )
    for ip_id, ip, mac, name, agent_id in interfaces:
        interface_id = generate_unique_id()
        connection.execute(
            sa.text(
                """
                    INSERT INTO setezor_agent_network_interface (
                        id, created_at,
                        ip, mac, name, agent_id,
                        is_default
                    )
                    VALUES (
                        :id, :created_at,
                        :ip, :mac, :name, :agent_id,
                        :is_default
                    )
                """,
            ),
            {
                "id": interface_id, "created_at": datetime.now(),
                "ip": ip, "mac": mac or "", "name": name, "agent_id": agent_id,
                "is_default": False
            }
        )
        op.execute(f"UPDATE network_ip SET interface_id = '{interface_id}' WHERE network_ip.id = '{ip_id}';")

    op.create_table('network_web_archive',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Название архива'),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Полная ссылка на таргет'),
    sa.Column('dns_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор DNS записи'),
    sa.ForeignKeyConstraint(['dns_id'], ['network_dns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для хранения web архивов'
    )

    row = list(
        connection.execute(sa.text(
            "select "
                "setezor_agent_in_project.id as agent_in_project_id, "
                "setezor_agent.id as agent_id, "
                "setezor_agent.user_id "
            "from project_task "
            "join "
                "setezor_agent_in_project on project_task.agent_id = setezor_agent_in_project.id "
            "join "
                "setezor_agent on setezor_agent.id = setezor_agent_in_project.agent_id "
            "group by "
                "setezor_agent_in_project.id, "
                "setezor_agent.id, "
                "setezor_agent.user_id"
        ))
    )
    op.add_column('project_task', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор пользователя'))
    op.alter_column('project_task', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Идентификатор агента',
               existing_comment='Идентификатор проекта',
               existing_nullable=True)
    op.drop_constraint(op.f('task_agent_id_fkey'), 'project_task', type_='foreignkey')

    for agent_in_project_id, agent_id, user_id in row:
        op.execute(f"UPDATE project_task SET agent_id = '{agent_id}', user_id = '{user_id}' WHERE project_task.agent_id = '{agent_in_project_id}';")

    op.alter_column('project_task', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор пользователя'))

    op.create_foreign_key(None, 'project_task', 'setezor_agent', ['agent_id'], ['id'])
    op.create_foreign_key(None, 'project_task', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_task', type_='foreignkey')
    op.drop_constraint(None, 'project_task', type_='foreignkey')
    op.create_foreign_key(op.f('task_agent_id_fkey'), 'project_task', 'setezor_agent_in_project', ['agent_id'], ['id'])
    op.alter_column('project_task', 'agent_id',
               existing_type=sa.VARCHAR(),
               comment='Идентификатор проекта',
               existing_comment='Идентификатор агента',
               existing_nullable=True)
    op.drop_column('project_task', 'user_id')
    op.drop_constraint(None, 'network_ip', type_='foreignkey')
    op.drop_column('network_ip', 'interface_id')
    op.drop_table('network_web_archive')
    op.drop_table('setezor_agent_network_interface')
    # ### end Alembic commands ###
