"""screenshooter

Revision ID: 5601b441367a
Revises: c62b2a47ad9c
Create Date: 2025-07-28 16:23:21.560443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5601b441367a'
down_revision: Union[str, None] = 'c62b2a47ad9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_dns_a_screenshot',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dns_a_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор DNS A записи'),
    sa.Column('screenshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор скриншота'),
    sa.ForeignKeyConstraint(['dns_a_id'], ['network_dns_a.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], ),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для хранения связи между DNS A записью и скриншотом'
    )
    op.add_column('setezor_agent', sa.Column('information', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Запускаемые таски'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setezor_agent', 'information')
    op.drop_table('network_dns_a_screenshot')
    # ### end Alembic commands ###
