"""delete sceenshot table

Revision ID: 747fefc50024
Revises: f37eba8bbf39
Create Date: 2025-12-03 13:26:58.039336

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from setezor.settings import PROJECTS_DIR_PATH



# revision identifiers, used by Alembic.
revision: str = '747fefc50024'
down_revision: Union[str, None] = 'f37eba8bbf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def change_screenshots(table_name: str):
    connection = op.get_bind()
    screenshots = list(connection.execute(text(
        "SELECT "
            f"{table_name}.id, "
            f"{table_name}.screenshot_id, "
            f"{table_name}.project_id, "
            f"{table_name}.scan_id, "
            f"screenshot.path "
        f"FROM {table_name} "
        f"JOIN screenshot ON screenshot.id = {table_name}.screenshot_id"
    )))
    screenshots_names = dict() # {old_name : new_name}
    for id, screenshot_id, project_id, scan_id, screenshot_path in screenshots:
        screenshots_path = os.path.join(PROJECTS_DIR_PATH, project_id, scan_id, "screenshots")
        old_screenshot_name = os.path.split(screenshot_path)[-1]
        screenshots_names[old_screenshot_name] = screenshots_names.get(old_screenshot_name, screenshot_id)
        op.execute(f"UPDATE {table_name} SET screenshot_id = '{screenshots_names.get(old_screenshot_name)}' WHERE id = '{id}';")
        old_screenshot = os.path.join(screenshots_path, old_screenshot_name)
        if not os.path.exists(old_screenshot):
            continue
        new_screenshot = os.path.join(screenshots_path, screenshots_names.get(old_screenshot_name))
        os.rename(old_screenshot, new_screenshot)


def upgrade() -> None:

    change_screenshots("network_port_software_vulnerability_screenshot")
    change_screenshots("network_dns_a_screenshot")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('network_dns_a_screenshot_screenshot_id_fkey'), 'network_dns_a_screenshot', type_='foreignkey')
    op.drop_constraint(op.f('network_port_software_vulnerability_screensh_screenshot_id_fkey'), 'network_port_software_vulnerability_screenshot', type_='foreignkey')
    op.drop_table('screenshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('network_port_software_vulnerability_screensh_screenshot_id_fkey'), 'network_port_software_vulnerability_screenshot', 'screenshot', ['screenshot_id'], ['id'])
    op.create_foreign_key(op.f('network_dns_a_screenshot_screenshot_id_fkey'), 'network_dns_a_screenshot', 'screenshot', ['screenshot_id'], ['id'])
    op.create_table('screenshot',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Путь до скриншота'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('screenshot_project_id_fkey1')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('screenshot_scan_id_fkey1')),
    sa.PrimaryKeyConstraint('id', name=op.f('screenshot_pkey1')),
    comment='Таблица предназначена для хранения скриншотов на веб-ресурсе'
    )
    # ### end Alembic commands ###
