"""last_time_seen_agent

Revision ID: ad48d87436e5
Revises: d0a4f55e9870
Create Date: 2025-06-25 14:29:07.670012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ad48d87436e5'
down_revision: Union[str, None] = 'd0a4f55e9870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setezor_agent', sa.Column('last_time_seen', sa.DateTime(), nullable=True, comment='Последний раз агент выходил на связь'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setezor_agent', 'last_time_seen')
    # ### end Alembic commands ###
