"""move logs from the database

Revision ID: b3be79b8b303
Revises: cf6ab0e68ad5
Create Date: 2025-10-22 14:55:37.798202

"""
import os
import json
import base64

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text, VARCHAR
from setezor.settings import PATH_PREFIX
from setezor.tasks.base_job import BaseJob
# The import is needed so that the class gets into the BaseJob subclasses.
from setezor.tasks.nmap_parse_task import NmapParseTask # noqa
from setezor.tasks.masscan_parse_task import MasscanLogTask # noqa
from setezor.tasks.scapy_logs_task import ScapyLogsTask # noqa
from setezor.tasks.wappalyzer_logs_task import WappalyzerLogsTask # noqa


# revision identifiers, used by Alembic.
revision: str = 'b3be79b8b303'
down_revision: Union[str, None] = 'cf6ab0e68ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_dns_a_screenshot', 'dns_id',
               existing_type=VARCHAR(),
               comment='Идентификатор DNS записи',
               existing_comment='Идентификатор DNS A записи',
               existing_nullable=False)
    # ### end Alembic commands ###

    connection = op.get_bind()
    rows_project_task = list(connection.execute(text(
        "SELECT "
            "id,"
            "project_id,"
            "scan_id,"
            "created_by,"
            "created_at,"
            "params "
        "FROM project_task"
    )))
    uniq_created_by = set()
    for id, project_id, scan_id, created_by, created_at, params_str in rows_project_task:
        params = json.loads(params_str)
        if (header_data := params.pop("file", None) or params.pop("log_file", None)):
            if created_by not in uniq_created_by:
                uniq_created_by.add(created_by)
            connection.execute(text(
                "UPDATE project_task "
                "SET params = :params "
                "WHERE id = :id"
            ), {
                "params": json.dumps(params, ensure_ascii=False),
                "id": id,
            })
            header, data = header_data.split(',')
            data = base64.b64decode(data)
            try:
                mime = header[header.index('/')+1:header.index(';')]
                data = data.decode('utf-8')
                if mime == "octet-stream":
                    mime = "txt"
            except:
                continue
            task_class = BaseJob.get_task_by_class_name(created_by)
            log_path = os.path.join(PATH_PREFIX, "projects", project_id, scan_id, task_class.logs_folder)
            if not os.path.exists(log_path):
                os.makedirs(log_path, exist_ok=True)
            log_file = os.path.join(log_path, f"{created_at}_{created_by}_{id}.{mime}")
            with open(log_file, 'w') as file:
                file.write(data)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_dns_a_screenshot', 'dns_id',
               existing_type=VARCHAR(),
               comment='Идентификатор DNS A записи',
               existing_comment='Идентификатор DNS записи',
               existing_nullable=False)
    # ### end Alembic commands ###
