"""Flag

Revision ID: bfa92278e898
Revises: 8c3c937660ca
Create Date: 2025-04-21 12:54:58.161111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bfa92278e898'
down_revision: Union[str, None] = '8c3c937660ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('flag', sa.Boolean(), nullable=True, comment='Флаг агента'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'flag')
    # ### end Alembic commands ###
