"""screenshots

Revision ID: c62b2a47ad9c
Revises: ad48d87436e5
Create Date: 2025-07-04 12:18:40.222323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c62b2a47ad9c'
down_revision: Union[str, None] = 'ad48d87436e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenshot',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Путь до скриншота'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для хранения скриншотов на веб-ресурсе'
    )
    op.drop_table('software_web_screenshot')
    op.add_column('network_port_software_vulnerability_screenshot', sa.Column('screenshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор скриншота уязвимости'))
    op.create_foreign_key(None, 'network_port_software_vulnerability_screenshot', 'screenshot', ['screenshot_id'], ['id'])
    op.drop_column('network_port_software_vulnerability_screenshot', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_port_software_vulnerability_screenshot', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Путь до скриншота'))
    op.drop_constraint(None, 'network_port_software_vulnerability_screenshot', type_='foreignkey')
    op.drop_column('network_port_software_vulnerability_screenshot', 'screenshot_id')
    op.create_table('software_web_screenshot',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Путь до скриншота'),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор ресурса'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='screenshot_project_id_fkey'),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name='screenshot_scan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='screenshot_pkey'),
    comment='Таблица предназначена для хранения скриншотов на веб-ресурсе'
    )
    op.drop_table('screenshot')
    # ### end Alembic commands ###
