"""join dns

Revision ID: cf6ab0e68ad5
Revises: 5601b441367a
Create Date: 2025-10-06 14:56:35.273466

"""
from typing import Sequence, Union

import json
from uuid import uuid4

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from setezor.db.entities import DNSTypes

# revision identifiers, used by Alembic.
revision: str = 'cf6ab0e68ad5'
down_revision: Union[str, None] = '5601b441367a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setezor_d_dns_type',
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Наименование типа DNS'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник типов DNS записей'
    )

    connection = op.get_bind()
    for dns_type in DNSTypes:
        connection.execute(
            sa.text(
                "INSERT INTO setezor_d_dns_type (created_at, id, name) "
                "VALUES (CURRENT_TIMESTAMP, :id, :name)"
            ),
            {"id": dns_type.value, "name": dns_type.name}
        )

    op.create_table('network_dns',
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dns_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор типа DNS'),
    sa.Column('target_ip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='Идентификатор домена'),
    sa.Column('value_domain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Идентификатор полученного домена'),
    sa.Column('ttl', sa.Integer(), nullable=True, comment='TTL'),
    sa.Column('extra_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Дополнительные данные в формате json'),
    sa.ForeignKeyConstraint(['dns_type_id'], ['setezor_d_dns_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], ),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], ),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], ),
    sa.ForeignKeyConstraint(['value_domain_id'], ['network_domain.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица предназначена для хранения DNS записей домена'
    )

    rows_dns_a = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, target_ip_id, target_domain_id FROM network_dns_a")))
    for row in rows_dns_a:
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, NULL,
                        NULL, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "extra_data": None,
                "dns_type_id": DNSTypes.A.value,
            }
        )

    rows_dns_ns = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, target_ip_id, target_domain_id, value_domain_id FROM network_dns_ns")))
    for row in rows_dns_ns:
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id,
                        NULL, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "extra_data": None,
                "dns_type_id": DNSTypes.NS.value,
            }
        )

    rows_dns_mx = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, target_ip_id, target_domain_id, value_domain_id, priority FROM network_dns_mx")))
    for row in rows_dns_mx:
        extra_data = {"priority": row.priority}
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id,
                        NULL, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "extra_data": json.dumps(extra_data),
                "dns_type_id": DNSTypes.MX.value,
            }
        )

    rows_dns_cname = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, record_value, target_ip_id, target_domain_id FROM network_dns_cname")))
    for row in rows_dns_cname:
        domain_row = connection.execute(
            text("SELECT id FROM network_domain WHERE domain = :domain"),
            {"domain": row.record_value}).fetchone()
        if domain_row:
            value_domain_id = domain_row.id
        else:
            value_domain_id = uuid4().hex
            connection.execute(
                text("""
                    INSERT INTO network_domain (id, domain, created_at, scan_id)
                    VALUES (:id, :domain, CURRENT_TIMESTAMP, :scan_id)
                """),
                {"id": value_domain_id, "domain": row.record_value, "scan_id": row.scan_id}
            )
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id,
                        NULL, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "value_domain_id": value_domain_id,
                "extra_data": None,
                "dns_type_id": DNSTypes.CNAME.value,
            }
        )

    rows_dns_txt = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, record_value, target_ip_id, target_domain_id FROM network_dns_txt")))
    for row in rows_dns_txt:
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, NULL,
                        NULL, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "extra_data": row.record_value,
                "dns_type_id": DNSTypes.TXT.value,
            }
        )

    rows_dns_soa = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, target_ip_id, target_domain_id, domain_nname_id, domain_rname_id, serial, refresh, retry, expire, ttl FROM network_dns_soa")))
    for row in rows_dns_soa:
        domain_rname = connection.execute(
            text("SELECT domain FROM network_domain WHERE id = :id"),
            {"id": row.domain_rname_id}).fetchone()

        extra_data = {
            "domain_rname": domain_rname.domain or "",
            "serial": row.serial,
            "refresh": row.refresh,
            "retry": row.retry,
            "expire": row.expire,
        }
        connection.execute(
            text("""
                INSERT INTO network_dns (
                    id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id,
                    ttl, extra_data, dns_type_id
                )
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id,
                        :ttl, :extra_data, :dns_type_id)
            """),
            {
                **row._mapping,
                "value_domain_id": row.domain_nname_id,
                "extra_data": json.dumps(extra_data),
                "dns_type_id": DNSTypes.SOA.value,
            }
        )

    op.drop_constraint(op.f('network_dns_a_screenshot_dns_a_id_fkey'), 'network_dns_a_screenshot', type_='foreignkey')
    op.alter_column( 'network_dns_a_screenshot', 'dns_a_id', new_column_name='dns_id', existing_type=sa.VARCHAR(), existing_nullable=False, existing_comment='Идентификатор DNS записи')
    op.create_foreign_key('network_dns_a_screenshot_dns_id_fkey', 'network_dns_a_screenshot', 'network_dns', ['dns_id'], ['id'])
    op.create_table_comment(
        'network_dns_a_screenshot',
        'Таблица предназначена для хранения связи между DNS записью и скриншотом',
        existing_comment='Таблица предназначена для хранения связи между DNS A записью и скриншотом',
        schema=None
    )

    op.alter_column('network_domain', 'domain', existing_type=sa.VARCHAR(), nullable=False, existing_comment='Доменное имя')

    op.drop_constraint(op.f('l4_software_dns_a_id_fkey'), 'network_port_software', type_='foreignkey')
    op.alter_column('network_port_software', 'dns_a_id', new_column_name='dns_id', existing_type=sa.VARCHAR(), existing_nullable=False, existing_comment='Идентификатор DNS записи')
    op.create_foreign_key('network_port_software_dns_id_fkey', 'network_port_software', 'network_dns', ['dns_id'], ['id'])

    op.drop_table('network_dns_a')
    op.drop_table('network_dns_cname')
    op.drop_table('network_dns_ns')
    op.drop_table('network_dns_mx')
    op.drop_table('network_dns_txt')
    op.drop_table('network_dns_soa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('network_port_software_dns_id_fkey', 'network_port_software', type_='foreignkey')
    op.alter_column('network_port_software', 'dns_id', new_column_name='dns_a_id', existing_type=sa.VARCHAR(), existing_nullable=False, existing_comment='Идентификатор DNS записи')
    op.create_foreign_key(op.f('l4_software_dns_a_id_fkey'), 'network_port_software', 'network_dns_a', ['dns_a_id'], ['id'])

    op.alter_column('network_domain', 'domain', existing_type=sa.VARCHAR(), nullable=True, existing_comment='Доменное имя')

    op.drop_constraint('network_dns_a_screenshot_dns_id_fkey', 'network_dns_a_screenshot', type_='foreignkey')
    op.alter_column( 'network_dns_a_screenshot', 'dns_id', new_column_name='dns_a_id', existing_type=sa.VARCHAR(), existing_nullable=False, existing_comment='Идентификатор DNS A записи')
    op.create_foreign_key(op.f('network_dns_a_screenshot_dns_a_id_fkey'), 'network_dns_a_screenshot', 'network_dns_a', ['dns_a_id'], ['id'])
    op.create_table_comment(
        'network_dns_a_screenshot',
        'Таблица предназначена для хранения связи между DNS A записью и скриншотом',
        existing_comment='Таблица предназначена для хранения связи между DNS записью и скриншотом',
        schema=None
    )

    op.drop_constraint(None, 'network_dns_a_screenshot', type_='foreignkey')
    op.create_foreign_key(op.f('network_dns_a_screenshot_dns_a_id_fkey'), 'network_dns_a_screenshot', 'network_dns_a', ['dns_a_id'], ['id'])
    op.drop_column('network_dns_a_screenshot', 'dns_id')
    op.create_table('network_dns_soa',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('domain_nname_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('domain_rname_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('serial', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Серийный номер'),
    sa.Column('refresh', sa.INTEGER(), autoincrement=False, nullable=False, comment='Обновление'),
    sa.Column('retry', sa.INTEGER(), autoincrement=False, nullable=False, comment='Попытка'),
    sa.Column('expire', sa.INTEGER(), autoincrement=False, nullable=False, comment='Истекает'),
    sa.Column('ttl', sa.INTEGER(), autoincrement=False, nullable=False, comment='TTL'),
    sa.ForeignKeyConstraint(['domain_nname_id'], ['network_domain.id'], name=op.f('dns_soa_domain_nname_id_fkey')),
    sa.ForeignKeyConstraint(['domain_rname_id'], ['network_domain.id'], name=op.f('dns_soa_domain_rname_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_soa_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_soa_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_soa_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_soa_target_ip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_soa_pkey')),
    comment='Таблица предназначена для хранения DNS SOA записей домена'
    )
    op.create_table('network_dns_txt',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_value', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Значение DNS записи'),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_txt_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_txt_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_txt_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_txt_target_ip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_txt_pkey')),
    comment='Таблица предназначена для хранения DNS TXT записей домена'
    )
    op.create_table('network_dns_mx',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('value_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False, comment='Приоритет'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_mx_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_mx_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_mx_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_mx_target_ip_id_fkey')),
    sa.ForeignKeyConstraint(['value_domain_id'], ['network_domain.id'], name=op.f('dns_mx_value_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_mx_pkey')),
    comment='Таблица предназначена для хранения DNS MX записей домена'
    )
    op.create_table('network_dns_ns',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.Column('value_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_ns_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_ns_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_ns_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_ns_target_ip_id_fkey')),
    sa.ForeignKeyConstraint(['value_domain_id'], ['network_domain.id'], name=op.f('dns_ns_value_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_ns_pkey')),
    comment='Таблица предназначена для хранения DNS NS записей домена'
    )
    op.create_table('network_dns_cname',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_value', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Значение DNS записи'),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_cname_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_cname_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_cname_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_cname_target_ip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_cname_pkey')),
    comment='Таблица предназначена для хранения DNS CNAME записей домена'
    )
    op.create_table('network_dns_a',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор проекта'),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Задача, породившая сущность'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='Дата-время создания сущности'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время изменения сущности'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата-время удаления сущности'),
    sa.Column('scan_id', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Идентификатор скана'),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_ip_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор IP адреса'),
    sa.Column('target_domain_id', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Идентификатор домена'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('dns_a_project_id_fkey')),
    sa.ForeignKeyConstraint(['scan_id'], ['project_scan.id'], name=op.f('dns_a_scan_id_fkey')),
    sa.ForeignKeyConstraint(['target_domain_id'], ['network_domain.id'], name=op.f('dns_a_target_domain_id_fkey')),
    sa.ForeignKeyConstraint(['target_ip_id'], ['network_ip.id'], name=op.f('dns_a_target_ip_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dns_a_pkey')),
    comment='Таблица предназначена для хранения DNS A записей домена'
    )

    connection = op.get_bind()

    rows_dns = list(connection.execute(text(
        "SELECT project_id, created_by, created_at, updated_at, deleted_at, scan_id, id, dns_type_id, target_ip_id, target_domain_id, value_domain_id, ttl, extra_data FROM network_dns")))

    for row in rows_dns:
        if row.dns_type_id == DNSTypes.A.value:
            connection.execute(sa.text("""
                INSERT INTO network_dns_a
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id)
            """), row._mapping)

        elif row.dns_type_id == DNSTypes.NS.value:
            connection.execute(sa.text("""
                INSERT INTO network_dns_ns
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id)
            """), row._mapping)

        elif row.dns_type_id == DNSTypes.MX.value:
            extra = json.loads(row.extra_data) if row.extra_data else {}
            connection.execute(sa.text("""
                INSERT INTO network_dns_mx
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, value_domain_id, priority)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id, :priority)
            """), {
                **row._mapping,
                "priority": extra.get("priority"),
            })

        elif row.dns_type_id == DNSTypes.CNAME.value:
            dom = connection.execute(sa.text(
                "SELECT domain FROM network_domain WHERE id = :id"
            ), {"id": row.value_domain_id}).fetchone()
            connection.execute(sa.text("""
                INSERT INTO network_dns_cname
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, record_value)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :record_value)
            """), {
                **row._mapping,
                "record_value": dom.domain if dom else None,
            })

        elif row.dns_type_id == DNSTypes.TXT.value:
            connection.execute(sa.text("""
                INSERT INTO network_dns_txt
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, record_value)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :record_value)
            """), {
                **row._mapping,
                "record_value": row.extra_data,
            })

        elif row.dns_type_id == DNSTypes.SOA.value:
            extra = json.loads(row.extra_data) if row.extra_data else {}
            rname_id = None
            if "domain_rname" in extra:
                dom = connection.execute(sa.text(
                    "SELECT id FROM network_domain WHERE domain = :d"
                ), {"d": extra["domain_rname"]}).fetchone()
                if dom:
                    rname_id = dom.id
                else:
                    res = connection.execute(sa.text(
                        "INSERT INTO network_domain (id, domain, created_at) VALUES (gen_random_uuid(), :d, CURRENT_TIMESTAMP) RETURNING id"
                    ), {"d": extra["domain_rname"]})
                    rname_id = res.fetchone()[0]

            connection.execute(sa.text("""
                INSERT INTO network_dns_soa
                    (id, project_id, created_by, created_at, updated_at, deleted_at,
                    scan_id, target_ip_id, target_domain_id, domain_nname_id, domain_rname_id,
                    serial, refresh, retry, expire, ttl)
                VALUES (:id, :project_id, :created_by, :created_at, :updated_at, :deleted_at,
                        :scan_id, :target_ip_id, :target_domain_id, :value_domain_id, :domain_rname_id,
                        :serial, :refresh, :retry, :expire, :ttl)
            """), {
                **row._mapping,
                "domain_rname_id": rname_id,
                "serial": extra.get("serial"),
                "refresh": extra.get("refresh"),
                "retry": extra.get("retry"),
                "expire": extra.get("expire"),
            })

    op.drop_table('network_dns')
    op.drop_table('setezor_d_dns_type')
    # ### end Alembic commands ###
