"""change asn

Revision ID: f37eba8bbf39
Revises: b3be79b8b303
Create Date: 2025-11-27 16:51:30.513672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f37eba8bbf39'
down_revision: Union[str, None] = 'b3be79b8b303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_asn', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Название ASN'))
    op.add_column('network_asn', sa.Column('org', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Название организации'))
    op.add_column('network_asn', sa.Column('isp', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Название интернет-провайдера'))
    op.add_column('network_asn', sa.Column('hosting', sa.Boolean(), nullable=True, comment='Является хостингом, узлом размещения или центром обработки данных'))
    op.add_column('network_asn', sa.Column('proxy', sa.Boolean(), nullable=True, comment='Является адресом выхода Proxy, VPN или Tor'))
    op.add_column('network_asn', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Название страны'))
    op.add_column('network_asn', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True, comment='Название города'))
    params = dict(
        existing_type = sa.INTEGER(),
        type_ = sqlmodel.sql.sqltypes.AutoString(),
        existing_comment = 'Номер ASN',
        existing_nullable = True
    )
    if op.get_bind().dialect.name == "postgresql":
        params["postgresql_using"] = "number::text"
    op.alter_column("network_asn", "number", **params)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_asn', 'number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_comment='Номер ASN',
               existing_nullable=True)
    op.drop_column('network_asn', 'city')
    op.drop_column('network_asn', 'country')
    op.drop_column('network_asn', 'proxy')
    op.drop_column('network_asn', 'hosting')
    op.drop_column('network_asn', 'isp')
    op.drop_column('network_asn', 'org')
    op.drop_column('network_asn', 'name')
    # ### end Alembic commands ###
