# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r setezor/requirements.txt
    - name: Test run
      run: |
        export SERVER_REST_URL=https://0.0.0.0:16661
        python setezor/setezor.py & setezor_pid=$?
        echo "Pid is $setezor_pid"
        sleep 5

        curl --insecure -s -o /dev/null -w "%{http_code}" https://0.0.0.0:16661/login
        status_code=$?
        if [[ $status_code="200" ]];
        then
            echo good;
        else
            echo 'Bad status code, status code is $status_code'
            exit 1
        fi
